### ISSUE TITLE
Address have neither input nor output

### ISSUE THREAD

**Issue by yiwesi** [citp/BlockSci#99]
Why does some addresses have neither an input nor a output?
For example: 
https://blockchain.info/address/1JPJ1ij5hoNAkEX5nDiYQXgtyeC1uvvv82
https://blockchain.info/address/1LXnPYpHTwQeWfBVnQZ4yDP23b57NwoyrP

Ouput:
> Balance:  0
Equiv:  EquivAddress()
In Txes:  []
In Txes Count:  0
Ins:  []
Out Txes:  []
Out Txes count:  0
Outs:  []
Txes:  []
Type:  Pay to pubkey hash
Adress String:  1LXnPYpHTwQeWfBVnQZ4yDP23b57NwoyrP
Find Multisigs:  []
First Tx:  Tx(len(txins)=1, len(txouts)=2, size_bytes=225, block_height=472353, tx_index=233848834)
Has been spent:  True
Pubkey:  b'\x02\x9aF\xf6\xfc\xc4m\xa5m\x9c\x0b\xe8\x7fvl\x10G\x87M\xf1}\x89w\x90Z\x1cw\xdf\x9525\xa0\x8d'
Pubkeyhash:  c0e8377e0fbe6c04f8d53bd0319e00b6e3c13cd6
revealed TX:  Tx(len(txins)=101, len(txouts)=46, size_bytes=16466, block_height=472357, tx_index=233856475)

Code:
> address = chain.address_from_string("1LXnPYpHTwQeWfBVnQZ4yDP23b57NwoyrP")
print("Balance: ", address.balance())
print("Equiv: ", address.equiv())
print("In Txes: ", address.in_txes())
print("In Txes Count: ", address.in_txes_count())
print("Ins: ", address.ins())
print("Out Txes: ", address.out_txes())
print("Out Txes count: ", address.out_txes_count())
print("Outs: ", address.outs())
print("Txes: ", address.txes())
print("Type: ", address.type)
print("Adress String: ", address.address_string)
print("Find Multisigs: ", address.find_multisigs())
print("First Tx: ", address.first_tx)
print("Has been spent: ", address.has_been_spent)
print("Pubkey: ", address.pubkey)
print("Pubkeyhash: ", address.pubkeyhash)
print("revealed TX: ", address.revealed_tx)

What me also confuses is, that the Pubkeyhash form BlockSci is `c0e8377e0fbe6c04f8d53bd0319e00b6e3c13cd6` and from blockchain.info it is `d63cc1e3b6009e31d03bd5f8046cbe0f7e37e8c0`

**Comment by hkalodner** [comment]
Hmm. The same issue of address outputs missing came up in a previous issue though I can't find it now. It appears to be a local issue that has happened to some people that I haven't hit. It's possibility a bug in the old version of the parser. Or something due to system configuration.

It should hopefully be resolved by regenerating the address database.

This can be achieved by deleting `addressDB` and `parser/addressDB.txt` and then running blocksci parser with `address-index-update` instead of update.

The difference between pubkeyhash form between blockchain.info is due to the endianness of the printout. The form they show is probably more canonical, but fixing this is non-trivial and I haven't seen any instances where this matters since the raw pubkeyhash format is rarely used.

**Comment by yiwesi** [comment]
I am aware of issue #89 But there was the problem that he tried to get inputs from an addresss that only have outputs. 
Back to my problem: Your proposed solution worked! Thanks.

Regarding the pubkeyhash confusing: Man I was blind! Now I see the different endiannesses. No need to fix it. If I need the other endianness I'll try to change it in my own script.

I don't know if you reading comments in already closed issues: So I have a question regarding #96 Is there a python function to get the raw hex code of a transaction? If not, could you please add it in the next release?

**Comment by hkalodner** [comment]
I remember #89, but I was thinking of something different that I can't find now. Maybe I imagined it :D. The endianness stuff is tough to be consistent about since the canonical display for different fields ends up having different endianness which is pretty strange. I've responded to your other question in #102, but to summarize, unfortunately this is not possible since BlockSci doesn't not maintain all information necessary to retrieve this.

**Comment by Haaroon** [comment]
This seems to happen to me all  the time with all of my chains, not sure why, `address_from_string` always returns null but `addresses_from_prefix` returns the address i am looking for, the above fix doesnt solve the problem.

**Comment by alex-btc** [comment]
@Haaroon Did you manage to solve the issue with `address_from_string` returning null? I have the same issue.

**Comment by Haaroon** [comment]
> @Haaroon Did you manage to solve the issue with `address_from_string` returning null? I have the same issue.

I believe it was because the code was not indexed correctly. I moved to an SSD and reindexed everything. However I know that blocksci is not maintained anymore

**Comment by alex-btc** [comment]
Thanks @Haaroon, it seems the problem is that I was looking for addresses in blocks after the last block I parsed.

Looking for old addresses work fine.

It's a shame blocksci is not maintained anymore, it's such a fantastic library! Even in the present state I am getting so much of it!

**Comment by Haaroon** [comment]
It's amazing and helped me tremendously during my research by speeding up the process.   This is why I'm now also working on Raphtory/Raphtory, which is a temporal graph analytics tool with blockchain as one of the main use cases.

**Comment by alex-btc** [comment]
Nice @Haaroon! I looked up Raphtory and it seems very nice, can you point me to a bitcoin example of use? Thanks!

**Comment by Haaroon** [comment]
@alex-btc  we have an example with ethereum here https://github.com/Raphtory/Raphtory/tree/master/examples/raphtory-example-ethereum
